redis:
  image: clescot/rancher-redis:27
  ports:
   - "6379"
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
#    io.rancher.sidekicks: redis-data
#  volumes_from:
#   - redis-data 

#redis-sentinel:
#  image: joshula/redis-sentinel
#  ports:
#   - 26379:26379

#redis-data:
#  tty: true
#  command:
#  - cat
#  image: clescot/rancher-redis:27
#  stdin_open: true
#  volumes:
#  - /data
#  labels:
#    io.rancher.container.start_once: true

#webdis:
#  image: 'anapsix/webdis'
#  ports:
#   - "7379:7379"
#  links:
#   - redis:redis
