version: '2'
services:
  redis-sentinel:
    image: monachus/rancher-redis-sentinel:latest
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.pull_image: always
  client:
    image: monachus/sak
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  redis:
    image: monachus/rancher-redis:latest
    volumes:
    - redis-data:/data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
