redis:
  image: clescot/rancher-redis:27
  ports:
   - "6379:6379"
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
   

#redis-sentinel:
#  image: joshula/redis-sentinel
#  ports:
#   - 26379:26379




webdis:
  image: 'anapsix/webdis'
  ports:
   - "7379:7379"
  links:
   - redis:redis
