redis:
  image: clescot/rancher-redis:28
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.sidekicks: redis-data
  volumes:
   - redis-data:/data

redis-sentinel:
  image: clescot/rancher-redis-sentinel:3
  ports:
   - "26379"
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
